# Rockchip RK3566 quad core EmbedFire LubanCat 1
BOARD_NAME="lubancat-1"
BOARDFAMILY="rk35xx"
BOARD_MAINTAINER=""
BOOTCONFIG="lubancat-rk3566_defconfig"
KERNEL_TARGET="edge,current"
FULL_DESKTOP="yes"
BOOT_LOGO="desktop"
BOOT_FDT_FILE="rockchip/rk3566-lubancat-1.dtb"
IMAGE_PARTITION_TABLE="gpt"
BOOT_SCENARIO="spl-blobs"
BOOTFS_TYPE="fat"
